/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as crossChainMessengerSol from "./CrossChainMessenger.sol";
export type { crossChainMessengerSol };
import type * as mocks from "./mocks";
export type { mocks };
